# Generated by Django 3.2.7 on 2021-09-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('server', models.IntegerField(primary_key=True, serialize=False)),
                ('last_update', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.IntegerField()),
                ('type', models.IntegerField()),
                ('data', models.BinaryField()),
            ],
            options={
                'unique_together': {('server', 'type')},
            },
        ),
        migrations.CreateModel(
            name='HouseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.IntegerField(db_index=True)),
                ('territory_id', models.IntegerField(db_index=True)),
                ('ward_id', models.IntegerField(db_index=True)),
                ('house_id', models.IntegerField(db_index=True)),
                ('price', models.IntegerField()),
                ('owner', models.CharField(max_length=256)),
                ('start_sell', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'unique_together': {('server', 'territory_id', 'ward_id', 'house_id')},
            },
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('param1', models.CharField(default='', max_length=64)),
                ('param2', models.CharField(default='', max_length=64)),
                ('record_time', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.housestate')),
            ],
        ),
    ]
